### PR TITLE
Fixing small bug in PMNS_Decay

### PR DESCRIPTION
**Pull request by vicacuen**
When changing multiple times between nu and nubar in PMNS_Decay a bug happens (which I didn't detect because I didn't try such a thing in my tests). I solved it by handling delta_cp in a different way (because for the decay case, the matrix is non-hermitian and you cannot just conjugate the matrix in the case they are antineutrinos, so the delta sign change is handled in the rotations in the case they are antineutrinos).

### CODE REVIEW

**Comment by joaoabcoelho** [comment]
I see you included a new implementation of `RotateH`. That's ok, but it seems to me it's a lot of repeated code that may be hard to maintain. Is there no way this can be done without completely copying most of the `RotateH` function in `PMNS_Base`?

**Comment by vicacuen** [comment]
I'll try to think in a way to do it next week. The thing is for decay the hamiltonian become non hermitian, so when the decay is added, if instead of neutrinos we are considering antineutrinos, it is not as simple as conjugating the lower triangle, (also, the matrix is not symetrical any more, so the upper part must also be saved). That's why I changed the code so into the rotations is where the code is taking into account if we have neutrinos or antineutrinos, by changing delta_cp value there. I know that makes the code slower, I'll try to think next week in a simplified way to do it and if I found one, commit it.

**Comment by vicacuen** [comment]
I've removed the RotateH in the Decay class and moved the isnumubar conjugation after the rotations just before the two hamiltonians are summed. I need to keep RotateHd because the same rotations that are done for Hms are needed for the decay hamiltonian, also I've add the option to consider the decay of the second mass state. In a few months I would like to revise the code and implement also visible decay, which is a bit more complicated, and some major changes will be needed.

**Comment by joaoabcoelho** [comment]
While we're looking at this, it seems to me the rotation of Hms and Hd are actually identical right? So maybe we should take the opportunity to actually make them use the same code, again to avoid duplication. I think all we need is to change the PMNS_Base rotation to include a matrix address as argument. Then you can give it either `fHms` or `fHd` and it should be fine.

For your own part, in fact it seems you could first add them and then rotate, to avoid rotating twice. The only issue may be that the diagonal elements of `fHt` before rotation will be complex, so maybe the rotation function doesn't work in the same way.

**Comment by vicacuen** [comment]
Indeed, I could change PMNS_Base so the rotation takes the matrix and rotate it so both matrixes can use the same code, I didn't think of it before because I didn't want to change the Base which is core to all. About adding them and rotating after that, that wouldn't work because rotations assume the matrix to be hermitian and also I need to store the upper triangle after the rotation, but before the sum (because onced summed the two matrixes upper and lower triangule are no longer just the conjugate of the other)

**Comment by vicacuen** [comment]
I changed the RotateH function and erased the RotateHd function I had in the decay class and it seems to work perfectly. Is it okay like that?

**Comment by joaoabcoelho** [comment]
Good. Just a small question. Is there any reason why you are using arrays for `fHd` and `fHt`? I think keeping everything as vectors may be better for consistency and it has advantages in accessing the dimensions and also if we want to extend to more than 3 flavours.

**Comment by vicacuen** [comment]
You are right, fHt and fHam are [3][3] because fHam is like that for PMNS_Fast, I'll adapt that and also the complexsolver which was adapted to only 3-dim and do a new commit tomorrow

**Comment by vicacuen** [comment]
Now it is generalized to n neutrinos, I've tested and it works as expected, if you need me to introduce more changes just tell me.

**Comment by joaoabcoelho** [comment]
Great! I'm happy with it. I'll merge now =)

**Pull request merged**
