### PR TITLE
LIV extension added

### PR DESCRIPTION
**Pull request by nrkhanchowdhury**
LIV extension added

### CODE REVIEW

**Comment by joaoabcoelho** [comment]
I'm getting compilation errors here due to redefinition of the `complex`. I had moved away from that naming convention to avoid ambiguities. Instead, I have a `typedef`' called `complexD` which you should use to refer to any `complex<double>` types.

**Comment by nrkhanchowdhury** [comment]
> I'm getting compilation errors here due to redefinition of the `complex`. I had moved away from that naming convention to avoid ambiguities. Instead, I have a `typedef` called `complexD` which you should use to refer to any `complex<double>` types.

I see! I was initially having errors with `complexD` and fell back to `complex`. However I changed it now. I guess it works for you now.

**Comment by joaoabcoelho** [comment]
Still missing two instances in `PMNS_LIV.h`

**Comment by nrkhanchowdhury** [comment]
> Still missing two instances in `PMNS_LIV.h`

Done! Sorry for the inconvenience.

**Pull request merged**
